name: Build & Push to Docker Hub

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🔧 Lowercase the repo name
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}  # Extract repo name (remove owner)
          echo "REPO=${REPO_NAME,,}" >> $GITHUB_ENV

      - name: 🛠️ Build and Push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:${{ github.sha }}
